# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCarritoTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_carritoTest(self):
    self.driver.get("https://pascualbravo.ingejei.com/shop/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-product:nth-child(2) .wp-block-button__link > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-product:nth-child(4) .wp-block-button__link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-product:nth-child(6) .wp-block-button__link > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-product:nth-child(8) .wp-block-button__link > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-color2-color > .has-medium-font-size:nth-child(6) .wp-block-navigation-item__label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-cart-items__row:nth-child(1) .wc-block-cart-item__remove-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-cart-items__row:nth-child(1) .wc-block-cart-item__remove-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-cart-items__row:nth-child(1) .wc-block-cart-item__remove-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-cart-item__quantity:nth-child(5) > .wc-block-cart-item__remove-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-cart-item__remove-link").click()
  
