# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPagoTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pagoTest(self):
    self.driver.get("https://pascualbravo.ingejei.com/shop/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-product:nth-child(3) .wp-block-button__link > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-color2-color > .has-medium-font-size:nth-child(6) .wp-block-navigation-item__label").click()
    self.driver.find_element(By.LINK_TEXT, "Proceder al pago").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "billing-country").click()
    dropdown = self.driver.find_element(By.ID, "billing-country")
    dropdown.find_element(By.XPATH, "//option[. = 'Colombia']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(47)").click()
    self.driver.find_element(By.ID, "billing-first_name").click()
    self.driver.find_element(By.ID, "billing-first_name").send_keys("Santiago")
    self.driver.find_element(By.ID, "billing-last_name").send_keys("Restrepo")
    self.driver.find_element(By.ID, "billing-address_1").click()
    self.driver.find_element(By.ID, "billing-address_1").send_keys("calle 923#12#534")
    self.driver.find_element(By.ID, "billing-city").click()
    self.driver.find_element(By.ID, "billing-city").send_keys("Medellin")
    self.driver.find_element(By.ID, "billing-state").click()
    dropdown = self.driver.find_element(By.ID, "billing-state")
    dropdown.find_element(By.XPATH, "//option[. = 'Antioquia']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#billing-state > option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-address-form__phone > label").click()
    self.driver.find_element(By.ID, "billing-phone").send_keys("312312353")
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-checkout-place-order-button__text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-checkout-place-order-button__text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
