# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistroTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registroTest(self):
    self.driver.get("https://pascualbravo.ingejei.com/registro-y-busqueda/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.LINK_TEXT, "Acceder").click()
    self.driver.find_element(By.LINK_TEXT, "Registrarse").click()
    self.driver.find_element(By.ID, "user_login").send_keys("lucas123")
    self.driver.find_element(By.ID, "user_email").click()
    self.driver.find_element(By.ID, "user_email").send_keys("tmppqla@acc1s.net")
    self.driver.find_element(By.ID, "wp-submit").click()
  
