# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCarritoPrueba():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_carritoPrueba(self):
    self.driver.get("http://localhost:8000/?page_id=4")
    self.driver.set_window_size(1050, 708)
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-quantity-selector__button--plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-panel__button").click()
    self.driver.find_element(By.ID, "wc-block-components-totals-coupon__input-coupon").send_keys("HOLA")
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-totals-coupon__button > .wc-block-components-button__text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-components-quantity-selector__button--minus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-cart-item__remove-link").click()
  
