# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAgregarProductoPrueba():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregarProductoPrueba(self):
    self.driver.get("http://localhost:8000/wp-admin/post-new.php?post_type=product")
    self.driver.set_window_size(1050, 708)
    self.driver.find_element(By.ID, "title").send_keys("Perro Caliente")
    self.driver.find_element(By.ID, "_regular_price").click()
    self.driver.execute_script("window.scrollTo(0,834)")
    self.driver.find_element(By.ID, "_regular_price").send_keys("8000")
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    element = self.driver.find_element(By.ID, "tinymce")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Rico perro con salsas de la casa</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "publish").click()
  
