# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogginPrueba():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logginPrueba(self):
    self.driver.get("http://localhost:8000/?page_id=6")
    self.driver.set_window_size(1050, 708)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".show-password-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".show-password-input").click()
    self.driver.find_element(By.ID, "rememberme").click()
    self.driver.find_element(By.ID, "rememberme").click()
    element = self.driver.find_element(By.ID, "rememberme")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin12")
    self.driver.find_element(By.CSS_SELECTOR, ".show-password-input").click()
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".woocommerce-form").click()
  
